### ISSUE TITLE
No Database Available

### ISSUE THREAD

**Issue by rohangandra** [harshrajdhote/Easy-Proctr#1]
Hi Harshraj,

I'd be glad if you can provide the database schema or the database you have used for this application.
I would like to set it up in my local and test it.

Thanks,
Rohan

**Comment by harshrajdhote** [comment]
Hello,
Please find the attached sql file.

Thanks & Regards,
Harshraj Dhote

**Comment by rohangandra** [comment]
Thanks for the resoponse, but could not find the attachment.
Could you reshare it again please.

**Comment by harshrajdhote** [comment]
https://drive.google.com/file/d/1QQwcMLW6_bQpz9hMCsGloGPyAYyj4cN3/view?usp=drivesdk

Download it frm here.
If you face any difficult while downloading let me know.

**Comment by rohangandra** [comment]
Thanks, I was able to set up the application but none of the features work in my local.
Would appreciate if you can let me know the steps involved to make the application work.
All I could see is some static data and none of the screens work as shared in the images of yours.

Thanks

**Comment by rushabh-wadkar** [comment]
@rohangandra Did you make this work? @harshrajdhote @RuchikaGuntewar Please help!

**Comment by harshrajdhote** [comment]
Hello @rushabh-wadkar , I have provided the sql file in above comment, but the project won't work directly you have to add your own code at some places to make it executable, there are few bugs on which you need to work if you want to proceed with project.
also we kept some portion static because of time constraint. :-)
